version: '3.8'

services:
  backend:
    build: .
    container_name: vlaas-backend
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - AWS_REGION=ap-south-1
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - DYNAMO_TABLE_NAME=Users
      - DYNAMO_ENDPOINT=http://dynamodb:8000
      - JWT_SECRET=supersecretkey
      - CLIENT_URL=http://localhost:5173
    depends_on:
      - dynamodb
    volumes:
      - .:/usr/src/app
    command: ["npm", "run", "dev"]

  dynamodb:
    image: amazon/dynamodb-local
    container_name: dynamodb
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"

volumes:
  dynamodb_data:
